export const icotransl_list: { [key: string]: { name: string, smile: string } } = {
    'coal': {name: 'Уголь', smile: '🏙'},
    'gas': {name: 'Газ', smile: '🏙'},
    'oil': {name: 'Нефть', smile: '🏙'},
    'slate': {name: 'Сланец', smile: '🏙'},
    'turf': {name: 'Торф', smile: '🏙'},
    'uranium': {name: 'Ураниум', smile: '🏙'},
    'iron': {name: 'Железные слитки', smile: '📏'},
    'golden': {name: 'Золотые слитки', smile: '🧈'},
    'artefact': {name: 'Артефакты', smile: '⚱️'},
    'crystal': {name: 'Караты', smile: '💎'},
    'worker': { name: 'Рабочие', smile: '👥'},
    'energy': { name: 'Энергия', smile: '⚡'},
    'gold': { name: 'Шекели', smile: '💰'},
}